[package]
name = "puente_balanzav1"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serialport = "4.2"
log = "0.4"
env_logger = "0.10"
regex = "1"
